- name: Deploy Website
  hosts: webservers
  vars:
    document_root: /var/www
    web_root: website
  tasks: 
    - name: Latest nginx is installed and present
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: Static website content is present
      copy:
        src: "{{ web_root }}"
        dest: "{{ document_root }}"
        mode: preserve
    - name: Nginx configuration applied
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart nginx
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted